variable "vpc_cidr" {}
variable "vpc_name" {}
variable "az1" {}
variable "pubsn1" {}
variable "pubsn1_cidr" {}
variable "az2" {}
variable "pubsn2" {}
variable "pubsn2_cidr" {}
variable "igw_name" {}
variable "pubsnrt" {}
variable "nat-gw_name" {}
variable "prvsnrt" {}
variable "prvsn1" {}
variable "prvsn1_cidr" {}
variable "prvsn2" {}
variable "prvsn2_cidr" {}
variable "prvsn3" {}
variable "prvsn3_cidr" {}
variable "prvsn4" {}
variable "prvsn4_cidr" {}
variable "all_cidr" {}