variable "region" {}
variable "vpc_cidr" {}
variable "ami" {}
variable "instance_type" {}
variable "instance_type_docker" {}
variable "az1" {}
variable "az2" {}
variable "pubsn1_cidr" {}
variable "pubsn2_cidr" {}
variable "prvsn1_cidr" {}
variable "prvsn2_cidr" {}
variable "prvsn3_cidr" {}
variable "prvsn4_cidr" {}
variable "all_cidr" {}
variable "instance-type_asg" {}